### ISSUE TITLE
[Bug]: No theme colors when using window.renderChart

### ISSUE THREAD

**Issue by anstadnik** [phibr0/obsidian-charts#103]
### Describe the bug

When using window.renderChart, there are no theme colors.

### Steps to reproduce

Plot a graph using window.renderChart.

### Expected Behavior

First graph should use theme colors.

### Additional context

<img width="840" alt="image" src="https://github.com/phibr0/obsidian-charts/assets/40110937/697b50d9-3e49-49b6-890b-f3ec22b75e53">

### Code

```yaml
type: line
    labels: [Monday,Tuesday,Wednesday,Thursday,Friday]
    series:
        - title: Title 1
          data: [1,2,3,4,5]
        - title: Title 2
          data: [5,4,3,2,1]
        - title: Title 3
          data: [8,2,5,-1,4]

```dataviewjs
const chartData = {
  type: 'line',
  data: {
    labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    datasets: [
      {
        label: 'Title 1',
        data: [1, 2, 3, 4, 5],
      },
      {
        label: 'Title 2',
        data: [5, 4, 3, 2, 1],
      },
      {
        label: 'Title 3',
        data: [8, 2, 5, -1, 4],
      }
    ]
  },
};

window.renderChart(chartData, this.container);

```
```


### Operating system

macOS
