### ISSUE TITLE
Radar Graph bug

### ISSUE THREAD

**Issue by Scarlov** [phibr0/obsidian-charts#11]
While using the radar graph I wanted to create a personal progress graph (kind of like "levelling" myself up) but came across a weird bug were typing this:

 ```chart
 	type: radar
 	labels: [Physical Strength, Coding, Languages, Maths, Chemistry]
 	series:
 		- title: Me now
 		  data: [2.5,2,3,2,1]
		- title: Me I want to be
 		  data: [4.5,5,4,3.5,3]
 	width: 50%
	fill: true
 ```
![image](https://user-images.githubusercontent.com/72456958/115687493-23e83b80-a352-11eb-8cd2-00a661573f4f.png)

 results in a relatively normal graph being formed, however when I changed the value of just the last label:

 ```chart
 	type: radar
 	labels: [Physical Strength, Coding, Languages, Maths, Chemistry]
 	series:
 		- title: Me now
 		  data: [2.5,2,3,2,2]
		- title: Me I want to be
 		  data: [4.5,5,4,3.5,3]
 	width: 50%
	fill: true
 ```
 
![image](https://user-images.githubusercontent.com/72456958/115687643-4d08cc00-a352-11eb-8521-872c09923ddb.png)

then the first graph goes all wacky. I am probably doing something wrong but just in case wanted to post that here.

**Comment by phibr0** [comment]
This is intended behavior. The Chart is cut off at the "bottom", so that it doesn't use unnecessary space. You can disable that behavior by adding the `beginAtZero` Modifier set to `true` or using the appropriate `Min` Modifier (see Readme for more information).

Just add the following line at the bottom:
`beginAtZero: true`

**Comment by Scarlov** [comment]
Thank you! Sorry to bother you for no reason 😅

**Comment by phibr0** [comment]
No Problem! I am here to help

**Comment by Scarlov** [comment]
Love your plugin by the way! Can't wait for that option to do graphs from tables

**Comment by phibr0** [comment]
Thanks! I will probably work on improving the Generator Modal first though, things like a live Preview etc.

**Comment by tranvnhan** [comment]
> This is intended behavior. The Chart is cut off at the "bottom", so that it doesn't use unnecessary space. You can disable that behavior by adding the `beginAtZero` Modifier set to `true` or using the appropriate `Min` Modifier (see Readme for more information).
> 
> Just add the following line at the bottom: `beginAtZero: true`

Hi. Could you give one example of how to use `Min` modifier? I don't know where to put it in my script.
Thanks.

**Comment by phibr0** [comment]
```yaml
type: radar
labels: [Physical Strength, Coding, Languages, Maths, Chemistry]
series:
- title: Me now
  data: [2.5,2,3,2,2]
  - title: Me I want to be
  data: [4.5,5,4,3.5,3]
width: 50%
fill: true
xMin: 0
```

or this

```yaml
type: radar
labels: [Physical Strength, Coding, Languages, Maths, Chemistry]
series:
- title: Me now
  data: [2.5,2,3,2,2]
  - title: Me I want to be
  data: [4.5,5,4,3.5,3]
width: 50%
fill: true
beginAtZero: true
```

should work
