### ISSUE TITLE
YAMLSyntaxError

### ISSUE THREAD

**Issue by 39mm** [phibr0/obsidian-charts#12]
Copied an example, but I'm getting a following error:

YAMLSyntaxError: A collection cannot be both a mapping and a sequence at line 1, column 5:
    type: line
    ^^^^^^^^^

```chart
 	type: line
 	labels: \[Monday,Tuesday,Wednesday,Thursday,Friday\]
 	series:
 	- title: Title 1
 	data: \[1,2,3,4,5\]
 	- title: Title 2
 	data: \[5,4,3,2,1\]
 	- title: Title 3
 	data: \[8,2,5,-1,4\]
 ```
I'm using Obsidian v0.11.13

I don't have any issue with YAML, not sure if I have up to date Yaml parser or how to check that.

I appreciate any suggestion. Thanks.

**Comment by phibr0** [comment]
As stated in the Readme you can't just copy the Examples from the Readme since the Indentation will be off and Obsidian will try to convert HTML to Markdown which causes issues. You can copy and paste the following into Obsidian **while holding `CTRL + SHIFT + V`:**

```yaml
type: line
labels: [Monday,Tuesday,Wednesday,Thursday,Friday]
series:
  - title: Titel1
    data: [1,2,3,4,5]
  - title: Titel2
    data: [5,4,3,2,1]
  - title: Title3
    data: [8,2,5,-1,4]
tension: 0.5
fill: true
```
