### ISSUE TITLE
YAMLParseError: All mapping items must start at the same column at line

### ISSUE THREAD

**Issue by ahlrodrigues** [phibr0/obsidian-charts#134]
Hello! I'm trying to create the chart below, but I'm getting an error. Could someone help me fix it?
I'm following the example from the website: [https://charts.phib.ro/Meta/Charts/Chart+Types/Line+Chart](https://charts.phib.ro/Meta/Charts/Chart+Types/Line+Chart).

Obsidian: 1.8.4

````
```chart
type: line
labels: [Início,Janeiro]
series:
    - title: Ruth
    data: [0,636]
    - title: Maykon
    data: [0,541]
    - title: João Vitor
    data: [0,651] 
    - title: Sara Raquel
    data: [0,532]
    - title: Ana Beatriz
    data: [0,622]
    - title: Sara Max.
    data: [0,711]
    - title: Jumara
    data: [0,90]
    - title: Gustavo
    data: [0,403]
```
````

ERROR:

````Couldn't render Chart:
YAMLParseError: All mapping items must start at the same column at line 5, column 1:

    - title: Ruth
    data: [0,636]
^
````
You might also want to look for further Errors in the Console: Press CTRL + SHIFT + I to open it.
