### ISSUE TITLE
[Bug]: Stepped lines parameter ignored in Chart from Table

### ISSUE THREAD

**Issue by eikelben** [phibr0/obsidian-charts#137]
### Describe the bug

The parameter `stepped: true` is being ignored when the chart is generated from a table.  
![Image](https://github.com/user-attachments/assets/0f0f5967-11bb-4021-aa05-9ed8d59eadac)

### Relevant errors (if available)

```shell
No errors generated
```

### Steps to reproduce

When generating a line chart from a table, the parameter `stepped: true` is utilized.  

### Expected Behavior

It functions correctly when manually assigned to each series (when NOT linking to a table). 
![Image](https://github.com/user-attachments/assets/9618b696-6bcd-4a54-91d1-68d5ef4a4334)

### Code

```yaml
type: line
stepped: true //causes no change
time: year
fill: false
tension: 0
width: 100%
spanGaps: true
id: exampleTable
```

### Operating system

macOS
