### ISSUE TITLE
[Bug]: Converting a chart into an image makes text very small

### ISSUE THREAD

**Issue by pablomayobre** [phibr0/obsidian-charts#138]
### Describe the bug

When converting charts to an image, the size of the chart is too large, resulting in very small text once scaled down by Obsidian.

### Relevant errors (if available)

```shell
None
```

### Steps to reproduce

So this is the original chart:

```chart
type: bar
labels: [2019,2020,2021,2022,2023,2024]
series:
  - title: Participants
    data: [170, 157, 131, 378, 384, 255]
  - title: Games
    data: [36, 39, 36, 65, 77, 49]
tension: 0.19
width: 100%
labelColors: false
fill: false
beginAtZero: false
bestFit: false
bestFitTitle: undefined
bestFitNumber: 0
```

![Image](https://github.com/user-attachments/assets/5a898010-97f1-4027-adc0-3fa2f651637e)

And when I convert to image

![Image](https://github.com/user-attachments/assets/ca73610b-6ea0-4d6c-92c1-b5bb3664b301)

This is the chart I get

![Image](https://github.com/user-attachments/assets/126bb54e-296c-4b3a-bea2-44e692af6268)

### Expected Behavior

I would like to see a chart like that on the first image

![Image](https://github.com/user-attachments/assets/5a898010-97f1-4027-adc0-3fa2f651637e)

### Additional context

This is similar to #41 except I'm not exporting to PDF, I'm converting to image to then use Pandoc to export.

### Code

```yaml
type: bar
labels: [2019,2020,2021,2022,2023,2024]
series:
  - title: Participants
    data: [170, 157, 131, 378, 384, 255]
  - title: Games
    data: [36, 39, 36, 65, 77, 49]
tension: 0.19
width: 100%
labelColors: false
fill: false
beginAtZero: false
bestFit: false
bestFitTitle: undefined
bestFitNumber: 0
```

### Operating system

Linux
