### ISSUE TITLE
Use CSV for source instead of  text

### ISSUE THREAD

**Issue by jorgb** [phibr0/obsidian-charts#17]
I would like to use a CSV to plot my chart. I think it could be very powerful to show the contents of any column plotted without cluttering the text with series that might run out of sync. Now that CSV seems to be supported by more and more plugins it is also a handy way to add data to Obsidian like book collections, or taking BP measurements, running stats etc for example.

For example;

```
chart
        type: line
        source: bp_stats.csv
        labels: Date 
        series:
          - title: Systolic
            data: Sys
          - title: Diastolic
            data: Dia
 ```

And the CSV looks like (generated with Libre Office):
```
Date,Sys,Dia
2021-08-15,135,80
2021-08-16,128,76
```
