### ISSUE TITLE
Possibility of having a line have a start and end without having to fill in the ones in between.

### ISSUE THREAD

**Issue by Braweria** [phibr0/obsidian-charts#26]
I am creating a burnup and burndown chart, and for that I want to have a line that starts at zero and ends at the scope. At the moment I have to calculate each point manually to write it down. This is what it looks like:

```
type: line
labels: [Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag, Sonntag]
series:
    - title: Scope
      data: [72,72,72,72,72,72,72]
    - title: Ideal
      data: [0,12,24,36,48,60,72]
    - title: Burnup
      data: [8, 16, 5]
beginAtZero: true
max: 72
fill: true
```

I checked the README, but didn't see an option for that. This is what it looks like:

![image](https://user-images.githubusercontent.com/62669899/139674447-80b82d21-ed8f-4f22-9630-d6c9687e35de.png)

Example for Burndown:

```
type: line
labels: [Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag, Sonntag]
series:
    - title: Ideal
      data: [72,60,48,36,24,12,0]
    - title: Burndown
      data: [72]
beginAtZero: true
```

![image](https://user-images.githubusercontent.com/62669899/139676992-f964c775-b1a7-4165-ac7f-f2bd5008375a.png)

**Comment by phibr0** [comment]
You can try this by adding `null` in between like so:

```yaml
type: line
labels: [Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag, Sonntag]
series:
    - title: Scope
      data: [72,null,null,null,null,null,72]
    - title: Ideal
      data: [0,12,24,36,48,60,72]
    - title: Burnup
      data: [8, 16, 5]
beginAtZero: true
max: 72
fill: true
spanGaps: true
```

And then set spanGaps to true!
