### ISSUE TITLE
[Bug]: Legend modifiers don't seem to work

### ISSUE THREAD

**Issue by kepano** [phibr0/obsidian-charts#49]
### Describe the bug

I might be doing something wrong but using `legend: false` or `legendPosition` doesn't seem to work with the example below. The legend is always present at the top.

```
chart
    type: bar
    labels: [2020,2021,2022,2023]
    legend: false
    series:
      - title: A
        data: [400,500,644,500]
      - title: B
        data: [200,300,500,600]
      - title: C
        data: [100,110,111,120]
      - title: D
        data: [50,60,189,450]
```

I have also tried with the `line` type with the same result

### Operating system

macOS
