### ISSUE TITLE
Support for https://github.com/tnichols217/obsidian-columns

### ISSUE THREAD

**Issue by Nedreow** [phibr0/obsidian-charts#60]
### Describe the feature

I would like to display multiple charts next to each other.

Currently the chart does not show up when inside a column.

### Does this fix a problem? If so, specify.

I cannot display charts side-by-side for easy comparison.

Example note:
``````
```chart
type: pie
labels: [Filled,Empty]
series:
  - title: Title 1
    data: [1, 11]
width: 40%
labelColors: true
legend: false
```

`````col
````col-md
flexGrow=1
===
test error
```chart
type: pie
labels: [Filled,Empty]
series:
  - title: Title 1
     data: [1, 11]
width: 40%
labelColors: true
legend: false
```
````

````col-md
flexGrow=1
===
test valid
```chart
type: pie
labels: [Filled,Empty]
series:
  - title: Title 1
    data: [1, 11]
width: 40%
labelColors: true
legend: false
```
````
`````
``````

Renders as:

![Charts side by side](https://user-images.githubusercontent.com/9559930/184969569-1d58be87-c0cc-4e7b-8238-ea70400d1c27.PNG)
