### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mattsbennett** [phibr0/obsidian-charts#76]
### Describe the bug

Width modifier not respected in Live Preview.

### Steps to reproduce

Create a pie chart with a width modifier (e.g. 400px). Width is respected in Reading view, but not Live Preview view.

### Expected Behavior

Width modifier is respected in Live Preview.

### Code

```yaml
type: pie
labels: [Money Supply (M1++),'Total Credit (Household, Financial & Non-financial)']
series:
  - title: Title 1
    data: [2108964000000,10126710000000]
tension: 0.2
width: 400px
labelColors: true
fill: true
beginAtZero: false
bestFit: false
bestFitTitle: undefined
bestFitNumber: 0
```

### Operating system

macOS

**Comment by JanUlrichR** [comment]
Can confirm this problem. A workaround is to add a custom stylesheet:
```css
canvas {
    width: 500px !important;
    height: 500px !important;
}
```
However this is still not the optimal solution.
