### ISSUE TITLE
[Bug]: Charts show black labels in dark mode

### ISSUE THREAD

**Issue by AbcAeffchen** [phibr0/obsidian-charts#86]
### Describe the bug

I use the API to view data collected using dataview as charts. Works perfectly fine but the axis and labels are all colored black which is unreadable when in dark mode.

![image](https://github.com/phibr0/obsidian-charts/assets/5396140/e4fd0625-6b11-4692-82d1-d04e5450d796)

### Steps to reproduce

All charts generated in a dataviewjs code block as well as in chart code blocks seem to have this issue. (provided an example in chart code block, but actually I need a solution for the dataviewjs case)

### Expected Behavior

The font and axis color should switch to white in dark mode or have an option to set the color explicitly. An other option would be to add an optional solid white background to the whole chart. 

### Additional context

I could not find a setting where to change the font and axis color explicitly. I looked into Chart.js, since this seems to be the underlying library. However, all I could find was to set a `Charts.options...` parameter but the `Charts` object is not available within `dataviewjs` code blocks.

### Code

```yaml
type: bar
labels: [A,B,C,D,E]
series:
  - title: test1
    data: [5,3,7,8,1]
  - title: test2
    data: [1,2,3,4,5]
tension: 0.23
width: 85%
labelColors: false
fill: false
beginAtZero: true
```

### Operating system

Linux
